apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-a-simple-app-test-attestations
  namespace: apps
spec:
  validationActions: [Deny]

  validationConfigurations:
    required: true
    verifyDigest: true

  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]

  matchImageReferences:
    - glob: "registry.iximiuz.com/a-simple-app-signed:*"

  attestors:
    - name: openbao
      cosign:
        key:
          kms: "openbao://gitless-gitops"
        ctlog:
            insecureIgnoreTlog: true
            insecureIgnoreSCT: true
            url: "https://rekor.sigstore.dev" # Even though it gets ignored, it has to be here

  attestations:
    - name: essentialSecurityTest 
      intoto:
        type: "https://in-toto.io/attestation/test-result/v0.1"

  validations:
    - expression: >-
        images.containers.map(image, verifyAttestationSignatures(image,
          attestations.essentialSecurityTest, [attestors.openbao])).all(e, e > 0)
      message: "Failed to verify attestation with OpenBao"
    - expression: >-
        images.containers.map(image, extractPayload(image, attestations.essentialSecurityTest).predicate.result == 'PASSED').all(e, e)
      message: "essentialSecurityTest is not PASSED"
